jobs:
  stage_0_job_0:
    name: ros2-tinyxml2-vendor ros2-mujoco-vendor ros2-mujoco-ros2-control-msgs ros2-rosidl-generator-dds-idl
      ros2-mujoco-3d-lidar tinyxml2-vendor rosidl-generator-dds-idl mujoco-vendor
      mujoco-ros2-control-msgs ros2-mujoco-ros2-control-plugins mujoco-3d-lidar ros2-mujoco-ros2-control
      mujoco-ros2-control-plugins mujoco-ros2-control
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v7
    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0
      with:
        pixi-version: latest
        cache: 'true'
        log-level: v
        frozen: 'true'
    - name: Build ros2-tinyxml2-vendor ros2-mujoco-vendor ros2-mujoco-ros2-control-msgs
        ros2-rosidl-generator-dds-idl ros2-mujoco-3d-lidar ros-lyrical-tinyxml2-vendor
        ros-lyrical-rosidl-generator-dds-idl ros-lyrical-mujoco-vendor ros-lyrical-mujoco-ros2-control-msgs
        ros2-mujoco-ros2-control-plugins ros-lyrical-mujoco-3d-lidar ros2-mujoco-ros2-control
        ros-lyrical-mujoco-ros2-control-plugins ros-lyrical-mujoco-ros2-control
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros2-tinyxml2-vendor ros2-mujoco-vendor ros2-mujoco-ros2-control-msgs
          ros2-rosidl-generator-dds-idl ros2-mujoco-3d-lidar ros-lyrical-tinyxml2-vendor
          ros-lyrical-rosidl-generator-dds-idl ros-lyrical-mujoco-vendor ros-lyrical-mujoco-ros2-control-msgs
          ros2-mujoco-ros2-control-plugins ros-lyrical-mujoco-3d-lidar ros2-mujoco-ros2-control
          ros-lyrical-mujoco-ros2-control-plugins ros-lyrical-mujoco-ros2-control
        BUILD_TARGET: linux-aarch64
      run: |
        export CI=github
        export GIT_BRANCH=${GITHUB_REF_NAME}
        export FEEDSTOCK_NAME=${GITHUB_REPOSITORY##*/}
        .scripts/build_unix.sh --target $BUILD_TARGET
    permissions:
      id-token: write
      attestations: write
name: build_linux_aarch64
on:
  push:
    branches:
    - buildbranch_linux_aarch64
